services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.30.7
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      TZ: "Europe/Berlin"
      GENERIC_TIMEZONE: "Europe/Berlin"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_UNVERIFIED_PACKAGES_ENABLED: "true"
      N8N_RUNNERS_TASK_TIMEOUT: "300"
      N8N_COMPRESSION_NODE_MAX_DECOMPRESSED_SIZE_BYTES: "2147483648"
      N8N_COMPRESSION_NODE_MAX_ZIP_ENTRIES: "5000"
      WEBHOOK_URL: "https://paperback-vault-objects-inspector.trycloudflare.com/"
      N8N_PROXY_HOPS: "1"

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    external: true
    name: n8n_data
